<?php
$sehir = $_GET['sehir'];

switch($sehir){

    case 'istanbul':

        $tpl->assign("sehir","İstanbul");
        $tpl->assign("sehir_k","istanbul");
        $tpl->assign("sehir_hakkinda","<p>T&uuml;rkiye denilince ş&uuml;phesiz ilk akla gelen şehir İstanbul&rsquo;dur. İstanbul T&uuml;rkiye'de sadece insan n&uuml;fusuyla &ouml;ne &ccedil;ıkmaz, aynı zamanda ekonominin de başkentidir. T&uuml;m bu &ouml;zelliklerinin yanında tarihi a&ccedil;ıdan da uzun bir ge&ccedil;mişe sahip olan İstanbul, k&uuml;lt&uuml;rel a&ccedil;ıdan da d&uuml;nyada b&uuml;y&uuml;k &ouml;nem taşır. Camileri, kiliseleri, tarihi yapıları, doğal g&uuml;zellikleri, jeopolitik konumu ile bir b&uuml;t&uuml;n olarak İstanbul d&uuml;nyada eşi benzeri zor bulunur &ouml;zelliklere sahiptir. G&uuml;n&uuml;m&uuml;z&uuml;n modern yaşamında artan n&uuml;fusu ile y&uuml;k&uuml; giderek artan İstanbul&rsquo;da yaşam bazen zor olsa da, pek &ccedil;ok insan i&ccedil;in vazge&ccedil;ilmez bir şehir olarak tanımlanır.</p>
<p>Karayolu taşımacılığı a&ccedil;ısından da b&uuml;y&uuml;k &ouml;nem taşıyan ve merkezi bir lokasyon olan bu sihirli şehre gitmek i&ccedil;in, farklı İstanbul <a href=\"{$site_adress}\">otob&uuml;s bileti</a> alternatifleri bulunmaktadır. Şehirler arası kaliteli ve konforlu bir yolculuk yapmak isteyen kişiler i&ccedil;in ilk akla gelen marka olan Ulusoy, m&uuml;şterilerine en uygun fiyatlarla İstanbul otob&uuml;s bileti se&ccedil;enekleri sunmaktadır. Uygun fiyatın m&uuml;şteri memnuniyeti i&ccedil;in yeterli bir kavram olmadığının farkında olan Ulusoy,&nbsp;İstanbul otob&uuml;s bileti&nbsp;satın alan kişilere uygun fiyatın yanında kaliteli ve konforlu bir yolculuk imkanı da sunar. Kara yolculuğu s&uuml;releri değişebilmekle birlikte, yolculuk &ccedil;eşitleri i&ccedil;inde en konfor gerektiren yolculuk şeklidir. Yolcuların bazen &ccedil;ok uzun saatler s&uuml;ren yolculukları boyunca ihtiyacı olan en başlıca şey konfor ve rahatlıktır. T&uuml;m bunların yanında g&uuml;venlik ve hizmet kalitesi gibi kullanıcı beklentileri ile &ouml;n plana &ccedil;ıkan kara yolculukları i&ccedil;in Ulusoy en iyisini sunmayı kendine hedef edinmiştir.</p>
<p>D&uuml;nya &uuml;zerindeki en eski şehirlerden birisi olan İstanbul; Roma İmparatorluğu, Bizans İmparatorluğu (Doğu Roma), Latin İmparatorluğu ve Osmanlı İmparatorluğu gibi sınırları olduk&ccedil;a geniş devletlere başkentlik yapmıştır. Yaşayan t&uuml;m imparatorlukların milletleri, dinleri, dilleri ve k&uuml;lt&uuml;rlerine ilişkin pek &ccedil;ok eseri de b&uuml;nyesinde barındıran İstanbul, bug&uuml;n d&uuml;nyanın &ouml;nde gelen turizm başkentlerinden biri olarak da dikkat &ccedil;ekmektedir. D&uuml;nyanın pek &ccedil;ok yerinden milyonlarca turist her mevsimde İstanbul&rsquo;u ziyaret etmektedir. Gezilecek ve g&ouml;r&uuml;lecek mekanlar a&ccedil;ısından olduk&ccedil;a geniş bir &ccedil;eşitliliğe sahip olan İstanbul&rsquo;da, sadece yabancı turistler i&ccedil;in değil, yerli turistler i&ccedil;in de olduk&ccedil;a farklı ve &ccedil;ok sayıda alternatif bulunmaktadır. Ulusoy, T&uuml;rkiye&rsquo;nin pek &ccedil;ok yerinden turist &ccedil;eken İstanbul i&ccedil;in en uygun fiyatı, en kaliteli hizmetle birleştirerek İstanbul otob&uuml;s bileti satın alma imkanı sunmaktadır. Sadece turistik geziler i&ccedil;in değil, işi sebebiyle İstanbul&rsquo;a gelen kullanıcılar da İstanbul otob&uuml;s bileti i&ccedil;in Ulusoy&rsquo;u tercih etmektedirler. &Ccedil;ağı yakalayarak hizmet standartları her ge&ccedil;en g&uuml;n daha da yukarı taşıyan Ulusoy, donanımlı 320 otob&uuml;sl&uuml;k filosu ile yıl i&ccedil;inde ortalama 3,5 milyon yolcu taşıyor.</p>
<p>İstanbul&rsquo;da yapılan son kazılarla birlikte şehrin tarihinin &ccedil;ok uzun yıllar &ouml;ncesine gittiği ortaya &ccedil;ıkarıldı. Yarımburgaz Mağarası&rsquo;ndan &ccedil;ıkarılan taş aletlerle İstanbul&rsquo;da ilkel insanın izlerinin 400 bin yıl &ouml;ncesine dayandığı, Anadolu Yakası&rsquo;nda yapılan kazılarda ise kentte tarım ve hayvancılığa dayanan ilk yerleşik insan topluluğunun İ.&Ouml;. 5 bin 500&rsquo;lerde Fikirtepe K&uuml;lt&uuml;r&uuml; olduğu g&ouml;r&uuml;lm&uuml;şt&uuml;r. T&uuml;m bu bulgular İstanbul&rsquo;un her d&ouml;nem insanların bu kenti yaşam alanı olarak &ouml;ncelikli olarak se&ccedil;tiğinin en &ouml;nemli g&ouml;stergelerindendir. İstanbul g&uuml;n&uuml;m&uuml;zde resmi olarak başkent olmasa da k&uuml;lt&uuml;r&uuml;n, tarihin, ekonominin ve yerleşimin başkenti olma &ouml;zelliğini devam ettirmekte ve korumaktadır. Jeopolitik a&ccedil;ıdan hala &ouml;nemini koruyan bu sihirli kent, hala Avrupa ve Asya kıtaları arasında k&ouml;pr&uuml; g&ouml;revi g&ouml;rmeye devam etmektedir. İstanbul&rsquo;un sahip olduğu t&uuml;m bu &ouml;zelliklerini yakından tanıyan Ulusoy, bu kente seyahat etmek isteyen m&uuml;şterilerine İstanbul&rsquo;a yakışır bir şekilde en kaliteli ve y&uuml;ksek standartlarda hizmet vermeye devam etmektedir. İstanbul <a href=\"{$site_adress}\">otob&uuml;s bileti</a> almak isteyen yolculara&nbsp;Ulusoy&nbsp;otob&uuml;s bileti&nbsp;sayfası &uuml;zerinden hızlı ve cazip fiyatlı hizmet veren Ulusoy, m&uuml;şteri memnuniyeti sıralamalarında en &uuml;st sıralarda yer almaya devam etmektedir.</p>
        ");

        $gezilecekler = array('Sultan Ahmet Camii' => 'https://www.google.com.tr/search?sa=X&espv=2&biw=1920&bih=1109&q=sultan+ahmet+camii&stick=H4sIAAAAAAAAAGOovnz8BQMDQzcHsxCnfq6-gaWliWWuEphpWJlWFq-lmJ1spZ-Tn5xYkpmfp5-cWVJZkl-eZ5VYUlKUmAwSK37E6Mst8PLHPWEpl0lrTl5jtOMirEdIkovNNa8EKCPEz8UrhbBag4FnR0zb87gqxtW_ztQ5MhzwzLgTK5kMAAz9bFaoAAAA&npsic=0&ei=DytjVOrlCsuXapirgIAK&ved=0CBoQ-BY&lei=LitjVJmsA43PaNWSgpgE', 'Ayasofya' => 'https://www.google.com.tr/search?sa=X&espv=2&biw=1920&bih=1109&q=ayasofya&stick=H4sIAAAAAAAAAGOovnz8BQMDQxcHsxCnfq6-gaWliWWuEgeImVRkWqilmJ1spZ-Tn5xYkpmfp5-cWVJZkl-eZ5VYUlKUmAwSK37E6Mst8PLHPWEpl0lrTl5jtOMirEdIkovNNa8EKCPEz8UrhbBZg4HnUsuvg6ffeIpOE2fLfr80KK_o8soFAMsGVi-nAAAA&npsic=0&ei=1UpjVK2QKNOP7Aa_g4DQDA&ved=0CB8Q-BY&lei=TUtjVIGHE6yV7AaDrYDACw', 'Topkapı Sarayı' => 'https://www.google.com.tr/search?sa=X&espv=2&biw=1920&bih=1109&q=topkap%C4%B1+saray%C4%B1&stick=H4sIAAAAAAAAAGOovnz8BQMDQzcHsxCnfq6-gaWliWWuEphpmJOeXK6lmJ1spZ-Tn5xYkpmfp5-cWVJZkl-eZ5VYUlKUmAwSK37E6Mst8PLHPWEpl0lrTl5jtOMirEdIkovNNa8EKCPEz8UrhbBag4EnVyr9zJdbB2bO0N1_c80fx8cH_A2VADyBxomoAAAA&npsic=0&ei=1UpjVK2QKNOP7Aa_g4DQDA&ved=0CCIQ-BY&lei=jktjVOrJGYHV7AbyioHgDA','Yerebatan Sarnıcı' => 'https://www.google.com.tr/search?sa=X&espv=2&biw=1920&bih=1109&q=yerebatan+sarn%C4%B1c%C4%B1&stick=H4sIAAAAAAAAAGOovnz8BQMDQzcHsxCnfq6-gaWliWWuEphpUmFoYaGlmJ1spZ-Tn5xYkpmfp5-cWVJZkl-eZ5VYUlKUmAwSK37E6Mst8PLHPWEpl0lrTl5jtOMirEdIkovNNa8EKCPEz8UrhbBag4HH7_ax3tsOuv0lBx7l6MrW8iwSW7cIAIIW8sioAAAA&npsic=0&ei=1UpjVK2QKNOP7Aa_g4DQDA&ved=0CCUQ-BY&lei=j0tjVOKsEMeP7AaRjIGIAQ','Süleymaniye Camii' => 'https://www.google.com.tr/search?sa=X&espv=2&biw=1920&bih=1109&q=s%C3%BCleymaniye+camii&stick=H4sIAAAAAAAAAGOovnz8BQMDQzcHsxCnfq6-gaWliWWuEphpVGiWm6SlmJ1spZ-Tn5xYkpmfp5-cWVJZkl-eZ5VYUlKUmAwSK37E6Mst8PLHPWEpl0lrTl5jtOMirEdIkovNNa8EKCPEz8UrhbBag4FnomXIwS-shY9lzI2cb3xJ8f379esxAAmrU0moAAAA&npsic=0&ei=1UpjVK2QKNOP7Aa_g4DQDA&ved=0CCgQ-BY&lei=k0tjVM6zEqGP7AbMgoCYDA');
        $tpl->assign('gezilecekler', $gezilecekler);

        $tpl->assign("location_key","318251");
        $tpl->assign("g_map","https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d769529.4938539197!2d29.358556959311507!3d41.11324611297478!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14caa7040068086b%3A0xe1ccfe98bc01b0d0!2zxLBzdGFuYnVsLCBUw7xya2l5ZQ!5e0!3m2!1str!2s!4v1415981632941");
        $tpl->assign("sehir_ulasim","http://www.iett.gov.tr/");
        break;

    case 'izmir':

        $tpl->assign("sehir","İzmir");
        $tpl->assign("sehir_k","izmir");
        $tpl->assign("sehir_hakkinda","<p>T&uuml;rkiye&rsquo;nin en kalabalık &uuml;&ccedil;&uuml;nc&uuml; kenti olma &ouml;zelliği taşıyan İzmir, Ege B&ouml;lgesi&rsquo;nin ortasında yer alan bir kıyı kentidir. Kıyı b&ouml;lgelerinde yer alan tatil merkezleriyle ve tarihi mekanlarıyla İzmir, aynı zamanda turistik a&ccedil;ıdan zengin bir kenttir. Yıl i&ccedil;inde yerli ve yabancı olduk&ccedil;a fazla turist &ccedil;eken kent i&ccedil;in, İzmir <a href=\"{$site_adress}\">otob&uuml;s bileti</a> satış işlemlerinizi <a target=\"_blank\" href=\"{$site_adress}\">www.otobus.com</a> &uuml;zerinden kolay ve pratik bir şekilde ger&ccedil;ekleştirebilir ve zaman kazanabilirsiniz.  </p>
<p>G&uuml;n&uuml;m&uuml;zde İzmir adının; Smyrna, Smira, Lesmira, İsmira, Samorna ve Smurna kelimelerinden d&ouml;n&uuml;şt&uuml;ğ&uuml; kabul edilir. Kentin ilk yerleşim yerleri olarak bug&uuml;nk&uuml; adıyla Bayraklı ve Tepekule civarında olduğu kabul edilen bir başka g&ouml;r&uuml;şt&uuml;r. Kentte en eski buluntular ise Bayraklı b&ouml;lgesinde İ.&Ouml;. 3000 yılına kadar dayandırılmaktadır. Antik d&ouml;nemlerin en b&uuml;y&uuml;k kentleri arasında yer alan Efes ise Roma İmparatorluğu d&ouml;neminden g&uuml;n&uuml;m&uuml;ze gelebilmiştir ve bug&uuml;n hala ayaktadır. K&uuml;lt&uuml;r olarak İyonya k&uuml;lt&uuml;r&uuml; zenginliklerini b&uuml;nyesinde taşıyan Efes, d&ouml;nemin &ouml;nemli ve dikkat &ccedil;eken sanat merkezleri arasındaydı. Bu tarihi g&uuml;zelliği ziyaret edip, keşfetmek isterseniz İzmir otob&uuml;s bileti satın alma işlemlerinizi Ulusoy aracılığıyla kolayca yapabilirsiniz. Birinci D&uuml;nya Savaşı sırasında Yunan ordusu tarafından işgal edilen İzmir, 9 Eyl&uuml;l 1922 tarihinde &ouml;zg&uuml;rl&uuml;ğ&uuml;ne yeniden kavuşmuştur. Bu tarih, g&uuml;n&uuml;m&uuml;zde İzmir i&ccedil;in olduk&ccedil;a &ouml;nemlidir ve T&uuml;rkiye&rsquo;nin en b&uuml;y&uuml;k &uuml;niversitelerinden biri olan Dokuz Eyl&uuml;l &Uuml;niversitesi&rsquo;ne adını vermiştir. İzmir, aynı zamanda 1984 yılında Ankara ve İstanbul ile birlikte b&uuml;y&uuml;kşehir &uuml;nvanı kazanmıştır.</p>
<p>Ege Denizi kıyısında yer alan kentin genelinde tipik Akdeniz iklimi hakimdir. Tıpkı Akdeniz ikliminde olduğu gibi yazın sıcaklık dereceleri g&uuml;neş ışınlarının gelme a&ccedil;ısına bağlıdır. İzmir i&ccedil;in en sıcak yaz ayı ortalaması 34 ile 45 derecelerde g&ouml;r&uuml;l&uuml;rken, en soğuk ay ortalaması 8 ile 10 derece arasında değişmektedir. Kentte bir yıl i&ccedil;inde sıfırın altına d&uuml;şen g&uuml;n sayısı 10 g&uuml;nden fazla olmamakla birlikte, 100 g&uuml;nden fazla g&uuml;n sıcaklık 30 derecenin &uuml;st&uuml;ndedir. Kent i&ccedil;in anlık hava durumu bilgisine sayfamızdan ulaşabilir ve İzmir otob&uuml;s bileti almadan &ouml;nce hazırlıklarınızı bu bilgilere g&ouml;re yapabilirsiniz. Şehirde aynı zamanda &lsquo;imbat&rsquo; adıyla bilinen ve sadece İzmir b&ouml;lgesine &ouml;zg&uuml;d&uuml;r. Genellikle yaz aylarında g&ouml;r&uuml;len imbat soğuk esen bir r&uuml;zgar t&uuml;r&uuml;d&uuml;r, kara ve denizin gece-g&uuml;nd&uuml;z arasındaki ısı farkından dolayı ortaya &ccedil;ıkmaktadır.</p>
<p>Kentte toplu taşıma; otob&uuml;s, metro ve vapur arasında b&uuml;y&uuml;k bir b&uuml;t&uuml;nl&uuml;kle sağlanır ve t&uuml;m ulaşım ara&ccedil;larına &lsquo;Kentkart&rsquo; adı verilen elektronik bir kartla binilebilir. İzmir otob&uuml;s bileti satın alma işlemlerinizi ger&ccedil;ekleştirdikten sonra sayfamızdaki &ldquo;İzmir Ulaşım&rdquo; kısmından kent i&ccedil;i ulaşım hakkında daha fazla bilgi edinebilirsiniz.</p>
<p>İzmir aynı zamanda T&uuml;rkiye&rsquo;nin en k&ouml;kl&uuml; ve kapsamı geniş fuarlarından biri olan İzmir Enternasyonal Fuarı&rsquo;da ev sahipliği yapmaktadır. Her yıl İzmir&rsquo;in kurtuluş g&uuml;n&uuml; olan 9 Eyl&uuml;l tarihinde a&ccedil;ılan İzmir Fuarı, ziyaret&ccedil;ilerine 10 g&uuml;n boyunca uluslararası niteliklerde hizmet vermektedir. İzmir <a href=\"{$site_adress}\">otob&uuml;s bileti</a> se&ccedil;imi yapmak i&ccedil;in T&uuml;rkiye&rsquo;nin &ouml;nc&uuml; taşımacılık firması olan Ulusoy&rsquo;u tercih edebilir ve daha konforlu yolculuklar yapabilirsiniz.</p>
        ");

        $gezilecekler = array('Kemeraltı Çarşısı' => 'https://www.google.com.tr/search?espv=2&q=izmir+kemeralt%C4%B1+%C3%A7ar%C5%9F%C4%B1s%C4%B1&stick=H4sIAAAAAAAAAGOovnz8BQMDQw8HsxCnfq6-gVGxUUWlEheYaZ6ebmSipZidbKWfk5-cWJKZn6efnFlSWZJfnmeVWFJSlJgMEit-xOjLLfDyxz1hKZdJa05eY7TjIqxHSJKLzTWvBCgjxM_FK4WwW4OB57BirbJXy84vj1vmdc7bpXarRffeSwD2ZMNYqQAAAA&npsic=0&sa=X&ei=cFpjVJaCCsGzacHTgrgD&ved=0CBoQ-BY&lei=tFpjVKO9C4KNaOmigdgH', 'Alsancak Garı' => 'https://www.google.com.tr/search?espv=2&q=izmir+alsancak+gar%C4%B1&stick=H4sIAAAAAAAAAGOovnz8BQMDQw8HsxCnfq6-gVGxUUWlEheIaZ6dUmCRrqWYnWyln5OfnFiSmZ-nn5xZUlmSX55nlVhSUpSYDBIrfsToyy3w8sc9YSmXSWtOXmO04yKsR0iSi801rwQoI8TPxSuFsFuDgedJa1nD-rNHdqlvPK_Quo3dmenKNjsA1pLkvakAAAA&npsic=0&sa=X&ei=cFpjVJaCCsGzacHTgrgD&ved=0CB0Q-BY&lei=tVpjVKzVHtbZaprogKAI', 'İzmir Saat Kulesi' => 'https://www.google.com.tr/search?espv=2&q=izmir+saat+kulesi&stick=H4sIAAAAAAAAAGOovnz8BQMDQw8HsxCnfq6-gVGxUUWlEheIaVyYZVqVpaWYnWyln5OfnFiSmZ-nn5xZUlmSX55nlVhSUpSYDBIrfsToyy3w8sc9YSmXSWtOXmO04yKsR0iSi801rwQoI8TPxSuFsFuDgSfs5KXZKQcOLlwk9bdqLZfYon-PSqIBxwDYNqkAAAA&npsic=0&sa=X&ei=cFpjVJaCCsGzacHTgrgD&ved=0CCAQ-BY&lei=t1pjVNCGIMnsaNPZgogM','Tarihi Asansör' => 'https://www.google.com.tr/search?espv=2&q=izmir+tarihi+asans%C3%B6r&stick=H4sIAAAAAAAAAGOovnz8BQMDQw8HsxCnfq6-gVGxUUWlEheYWVhiWlSspZidbKWfk5-cWJKZn6efnFlSWZJfnmeVWFJSlJgMEit-xOjLLfDyxz1hKZdJa05eY7TjIqxHSJKLzTWvBCgjxM_FK4WwW4OB53B8q3ScwWzLY2Y_E3Ukln-Y0pblCgDwLLa7qQAAAA&npsic=0&sa=X&ei=cFpjVJaCCsGzacHTgrgD&ved=0CCMQ-BY&lei=-1pjVLriN8TZat60gPAG','Beymen Konak Pier' => 'https://www.google.com.tr/search?espv=2&q=izmir+konak+pier&stick=H4sIAAAAAAAAAGOovnz8BQMDQw8HsxCnfq6-gVGxUUWlEheYWVhimm2upZidbKWfk5-cWJKZn6efnFlSWZJfnmeVWFJSlJgMEit-xOjLLfDyxz1hKZdJa05eY7TjIqxHSJKLzTWvBCgjxM_FK4WwW4OB5zSPhdLpGovgJu8JLX8Wud5O3dz4AQDoIuoFqQAAAA&npsic=0&sa=X&ei=cFpjVJaCCsGzacHTgrgD&ved=0CCYQ-BY&lei=_FpjVNziLpDjaNCxgYAD');
        $tpl->assign('gezilecekler', $gezilecekler);

        $tpl->assign("location_key","318290");
        $tpl->assign("g_map","https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d100032.95525925345!2d27.079717149999997!3d38.417675!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14bbd862a762cacd%3A0x628cbba1a59ce8fe!2zxLB6bWlyLCBUw7xya2l5ZQ!5e0!3m2!1str!2s!4v1416229616355");
        $tpl->assign("sehir_ulasim","http://www.eshot.gov.tr/HareketSaatleri.aspx?TIP=Hatlar&HatNo=5&AspxAutoDetectCookieSupport=1");
        break;

    case 'ankara':

        $tpl->assign("sehir","Ankara");
        $tpl->assign("sehir_k","ankara");
        $tpl->assign("sehir_hakkinda","<p>Türkiye’nin başkenti ve ikinci en kalabalık şehri olan Ankara nüfusunun yaklaşık dörtte 3’ü memuriyet, ulaşım, haberleşme ve ticaret sektörlerinde çalışmaktadır. Ankara aynı zamanda Türkiye’nin en çok üniversiteye sahip ili olmakla birlikte, üniversite diplomalı kişi oranı Türkiye ortalamasının iki katıdır. Ankara sokaklarında karşılaşacağınız kişilerin büyük bir çoğunluğu ya öğrenci, ya memur ya da askerdir. Görev ya da eğitim sebebiyle bu şehre gidecekseniz Ankara otobüs bileti satın alma işlemlerinizi <a href=\"{$site_adress}\" target=\"_blank\">www.otobus.com</a> üzerinden kolayca yapabilirsiniz. </p>
                        <p>Bilinen en eski tarihi Eski Taş Çağı’na (10 bin yıl öncesi) kadar ulaşan Ankara; Hitit, Frigyalılar, Lidyalılar, Pers, Galatlar, Roma, Bizans, Selçuklu ve Osmanlı imparatorluklarının hakimiyetinde olmuştur. Ankara toprakları üzerinde yaşayan uygarlıklar kente eşi görülmemiş zenginlikler bırakmıştır. Ankara toprakları üzerinde bulunan höyüklerden çıkarılan pek çok kalıntı, günümüzde ziyaretçilere açık bir şekilde müzelerde sergilenmektedir. Sikkeyi icat ettikleri kabul edilen Frig'lerin doğuşu da bu kentin toprakları üzerinde başlamıştır. Selçuklu ve Osmanlı dönemlerinin ardından Kurtuluş Savaşı döneminde de önemli bir konuma sahip olan Ankara, 13 Ekim 1923 tarihinde başkent ilan edilmiştir ve günümüzde hala Türkiye Cumhuriyeti’nin başkenti olmaya devam etmektedir. Başkent olması sebebiyle pek çok resmi kuruma da ev sahipliği yapan kentte, kara yolu ulaşımı tercih edilen ulaşım şekillerindendir biridir. Türkiye’nin öncü taşımacılık şirketlerinden biri olan Ulusoy ile Ankara otobüs bileti satın alma işlemlerinizi kolayca ve hızlı bir şekilde yapabilirsiniz.</p>
                        <p>İklimsel olarak karasal iklim özelliklerini taşıyan Ankara, İç Anadolu Bölgesi’nde yer alır. Karasal iklimin neredeyse tüm özelliklerini taşıyan Ankara’da kışlar soğuk ve kar yağışlı geçerken, yazlar ise kurak ve sıcak geçmektedir. Karasal iklimin bir diğer özelliği olan gece ve gündüz arasındaki sıcaklık farklarının yanında, kış ve yaz ayları arasında da oldukça önemli sıcaklık farkları görülmektedir. Ankara’nın bilinen en sıcak ayları Temmuz ve Ağustos iken, en soğuk ayı ise Ocak ayıdır. Yüz ölçümü olarak geniş topraklara yayılan kentte, ilçeler arasında sıcaklık veya yağış farklılıkları da oluşmaktadır. Ankara otobüs bileti satın almadan önce sayfamızdan gideceğiniz tarihe göre kentin sıcaklık değerleri hakkında bilgi edinebilir ve hazırlıklarınızı buna göre yapabilirsiniz.</p>
                        <p>Aynı zamanda Ankara Kedisi, Ankara Tavşanı ve Ankara Keçisi olarak bilinen hayvan türlerine de isim sahipliği yapan kentin, Ankara Kedisi kaynaklı kent logoları da bulunmaktadır. “Ankara” ismini Frigya ve Yunanca dilindeki Aykupa (anküra olarak telaffuz edilir) kelimelerinden alan Ankara, kelime anlamı olarak “gemi çapası” demektir.</p>
                        <p>Karayolu taşımacılığı, konforun en öncelikli geldiği yolculuk çeşidi olarak ön plana çıkmaktadır. Bazen onlarca saat sürebilen kara yolculukları sırasında yolcular, olabildiğinde konforlu ve rahat bir yolculuk geçirmek isterler. Ulusoy’a ait web sitesi üzerinden online olarak satın alınabilen Ankara otobüs bileti, konforlu şehirler arası yolculuklarınız için sadece bir başlangıç olacak. Ankara-İstanbul arasında en çok sefer düzenleyen firma olan Ulusoy, Ankara otobüs bileti konusunda da kullanıcılarına kolay ve pratik satış imkanları sunmaktadır. Pratik ve kolay bir şekilde Ankara otobüs bileti satın almak&nbsp;<a href=\"{$site_adress}/\" target=\"_blank\">www.otobus.com</a>&nbsp;ile bir tık kadar yakınınızda!</p>
                    ");

        $gezilecekler = array('Anıtkabir' => 'https://www.google.com.tr/search?espv=2&amp;q=an%C4%B1tkabir&amp;stick=H4sIAAAAAAAAAGOovnz8BQMDQzsHsxC7fq6-QVZluRIniGFqYJJmoqWYnWyln5OfnFiSmZ-nn5xZUlmSX55nlVhSUpSYDBIrfsTozS3w8sc9YSmnSWtOXmO04SKsR0ici801rwQoI8TLxS0Fs1iDgSdYRCyOp9Lr0Se3VR8sqw1zf6qI_AIAfjMcGaQAAAA&amp;npsic=0&amp;sa=X&amp;ei=HFRjVNSsI6zX7QbF6oEo&amp;ved=0CBoQ-BY&amp;lei=XlRjVIXABrCS7AaO2YDwBg', 'Kocatepe Camii' => 'https://www.google.com.tr/search?espv=2&amp;q=ankara+kocatepe+camii&amp;stick=H4sIAAAAAAAAAGOovnz8BQMDQwcHsxC7fq6-QVZluRIXiGFkXmBhkK6lmJ1spZ-Tn5xYkpmfp5-cWVJZkl-eZ5VYUlKUmAwSK37E6M0t8PLHPWEpp0lrTl5jtOEirEdInIvNNa8EKCPEy8UtBbNZg4Hn86H3WT4x10PzTSISHh1ZsVSIc9UsAIsGxIulAAAA&amp;npsic=0&amp;sa=X&amp;ei=dlRjVKmpE4q07ga2r4HwAw&amp;ved=0CCAQ-BY&amp;lei=eVRjVKTSDcqf7gbk1YCgCQ', 'Kurtuluş Savaşı Müzesi' => 'https://www.google.com.tr/search?espv=2&amp;q=ankara+kurtulu%C5%9F+sava%C5%9F%C4%B1+m%C3%BCzesi&amp;stick=H4sIAAAAAAAAAGOovnz8BQMDQwcHsxC7fq6-QVZluRIXiGFmUphtbKqlmJ1spZ-Tn5xYkpmfp5-cWVJZkl-eZ5VYUlKUmAwSK37E6M0t8PLHPWEpp0lrTl5jtOEirEdInIvNNa8EKCPEy8UtBbNZg4Hnl3bv1jyFls5d0zhu3toXeir24_rDAISIPpSlAAAA&amp;npsic=0&amp;sa=X&amp;ei=dlRjVKmpE4q07ga2r4HwAw&amp;ved=0CCMQ-BY&amp;lei=uVRjVOCaH6SE7gbX0YHYDg','Atakule' => 'https://www.google.com.tr/search?espv=2&amp;q=atakule&amp;stick=H4sIAAAAAAAAAGOovnz8BQMDQzsHsxC7fq6-QVZluRIniGGaVVGUpaWYnWyln5OfnFiSmZ-nn5xZUlmSX55nlVhSUpSYDBIrfsTozS3w8sc9YSmnSWtOXmO04SKsR0ici801rwQoI8TLxS0Fs1iDgcdYnfXSeqaATRlstzfuPzDLlS3I6AkALlZJ66QAAAA&amp;npsic=0&amp;sa=X&amp;ei=dlRjVKmpE4q07ga2r4HwAw&amp;ved=0CCYQ-BY&amp;lei=ulRjVKiXGLPG7Ab0hoDoAg','Atatürk Orman Çiftliği' => 'https://www.google.com.tr/search?espv=2&amp;q=atat%C3%BCrk+orman+%C3%A7iftli%C4%9Fi&amp;stick=H4sIAAAAAAAAAGOovnz8BQMDQwcHsxC7fq6-QVZluRIXiGFcaWlslqOlmJ1spZ-Tn5xYkpmfp5-cWVJZkl-eZ5VYUlKUmAwSK37E6M0t8PLHPWEpp0lrTl5jtOEirEdInIvNNa8EKCPEy8UtBbNZg4Fnrrmf3YZbSZ5rL3O-FnZays9ucNgTALsYlTmlAAAA&amp;npsic=0&amp;sa=X&amp;ei=dlRjVKmpE4q07ga2r4HwAw&amp;ved=0CCkQ-BY&amp;lei=vlRjVIrVGc6S7AbsrIGICA');
        $tpl->assign('gezilecekler', $gezilecekler);

        $tpl->assign("location_key","316938");
        $tpl->assign("g_map","https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d195884.72011687083!2d32.767872999999994!3d39.90337650000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14d347d520732db1%3A0xbdc57b0c0842b8d!2sAnkara%2C+T%C3%BCrkiye!5e0!3m2!1str!2s!4v1416229536122");
        $tpl->assign("sehir_ulasim","http://map.ego.gov.tr:8080/ego/index.aspx");
        break;

    case 'bursa':

        $tpl->assign("sehir","Bursa");
        $tpl->assign("sehir_k","bursa");
        $tpl->assign("sehir_hakkinda","<p>T&uuml;rkiye&rsquo;nin en kalabalık 4&rsquo;&uuml;nc&uuml; ili olan Bursa&rsquo;nın kent tarihi 7 bin yıl &ouml;ncesine kadar gitmektedir. Ilıpınar H&ouml;y&uuml;ğ&uuml;&rsquo;nde yapılan kazılarda şehrin yerleşim tarihinin M.&Ouml;. 5200 yıl &ouml;ncelerine kadar gittiği tespit edilmiştir. Kentte ayrıca; M.&Ouml;. 2500 yılına dayanan Demirtaş H&ouml;y&uuml;ğ&uuml; ile M.&Ouml;. 2700 yılına ait &Ccedil;akırk&ouml;y H&ouml;y&uuml;ğ&uuml; bulunur. Kentin asıl kuruluş tarihi ise M.&Ouml;. 3. y&uuml;zyıla dayanır. Prusa adıyla Bithynialılar ve Prusiaslılar tarafından kurulan Bursa&rsquo;nın ilk yerleşim yeri İznik G&ouml;l&uuml; &ccedil;evresi olarak kabul edilir. Sadece bu b&ouml;lgede Taş Devri&rsquo;ne ait olduğu anlaşılan 7 ayrı h&ouml;y&uuml;k bulunur. Kent stat&uuml;s&uuml;ne gelmesinin ardından etrafı surlarla &ccedil;evrilen Bursa, Hannibal&rsquo;ın Roma İmparatoru ile yaptığı savaşı kaybetmesi ve 1. Prusias&rsquo;a sığınmasını ve ardından da b&ouml;lgede Hannibal&rsquo;a duyulan saygıyla birlikte onun onuruna 1. Prusias tarafından kurulmuştur. Bithynia Krallığı M.&Ouml;. 74 yılında Roma İmparatorluğu&rsquo;na bağlanmış ve kent &ouml;nce Romalıların, ardından da Bizanslıların ili olarak varlığını devam ettirmiştir. G&uuml;n&uuml;m&uuml;zde Bizans&rsquo;a ait mezar stelleri ve &ccedil;eşitli mimari eser, seramik ve sikkeler Bursa Arkeoloji M&uuml;zesi b&uuml;nyesinde ziyaret&ccedil;ilerine sergilenmektedir. Şehri ziyaret etmeden &ouml;nce gezilecek yerler hakkında daha fazla bilgiye sayfalarımızdan ulaşabilir ve Bursa otob&uuml;s bileti satın alma işleminizi online olarak ger&ccedil;ekleştirebilirsiniz. &nbsp;</p>
<p>Aynı zamanda Osmanlı Devleti&rsquo;nin ilk başkenti olma &ouml;zelliğini de taşıyan Bursa&rsquo;da, g&uuml;n&uuml;m&uuml;zde hala Osmanlı&rsquo;dan kalan &ccedil;ok sayıda tarihi eser bulunmaktadır. Birinci D&uuml;nya savaşının ardından İtilaf Devletleri tarafından işgal edilen Bursa, iki yıl, iki ay ve iki g&uuml;nl&uuml;k işgalin ardından 11 Eyl&uuml;l 1922&rsquo;de kurtarılmıştır. 11 Eyl&uuml;l tarihi g&uuml;n&uuml;m&uuml;zde hala Bursa&rsquo;nın Kurluluş g&uuml;n&uuml; olarak &ccedil;eşitli etkinliklerle kentte kutlanmaktadır. Cumhuriyet&rsquo;in kurulmasıyla birlikte o zamanki kent n&uuml;f&uuml;sunun 3&rsquo;te birini oluşturan gayrim&uuml;slimler şehri terk etmiş, yerine M&uuml;badele G&ouml;&ccedil;menleri olarak da bilinen Balkan g&ouml;&ccedil;menleri kentte gelmiştir. Genelde ticaretle uğrraşan gayrim&uuml;limlerin yerine gelen M&uuml;badele G&ouml;&ccedil;menleri&rsquo;nin tarım ve &ccedil;ift&ccedil;ilikle uğraşması, yerel dili bilmemeleri gibi etkenler Bursa&rsquo;nın b&uuml;y&uuml;k bir k&uuml;lt&uuml;rel d&ouml;n&uuml;ş&uuml;m ge&ccedil;irmesini sağlamıştır. Uyum s&uuml;recinin ardından sanayi alanında b&uuml;y&uuml;k atılımlar yapan Bursa, g&uuml;n&uuml;m&uuml;zde &uuml;lkemizin &ouml;nemli ticari kentlerinden biridir. Bursa otob&uuml;s bileti satın alma işlemlerinizi ger&ccedil;ekleştirmeden &ouml;nce sayfalarımızdan kentle ilgili daha fazla bilgiye ulaşabilir, <a href=\"{$site_adress}\" target=\"_blank\">www.otobus.com</a> &uuml;zerinden bilet satın alma işlemlerinizi ger&ccedil;ekleştirebilirsiniz. &nbsp;</p>
<p>Genelde ılıman bir iklimin hakim olduğu kent, denizden 155 metre y&uuml;kseklikte konumlanmıştır. Y&uuml;z &ouml;l&ccedil;&uuml;m&uuml; olarak geniş topraklara sahip kentte iklim il&ccedil;elere g&ouml;re b&uuml;y&uuml;k farklılıklar g&ouml;sterebilmektedir. Deniz kenarında yer alan Kuzey il&ccedil;elerinde Marmara Denizi&rsquo;nin etkisiyle iklim yumuşakken, G&uuml;ney&rsquo;de yer alan dağ il&ccedil;elerinden Uludağ&rsquo;ın sert iklimi g&ouml;r&uuml;lmektedir. Bursa&rsquo;nın en soğuk ayları Temmuz ve Eyl&uuml;l iken, en soğuk ayları Şubat ve Mart olarak bilinir. Y&uuml;z&ouml;l&ccedil;&uuml;m&uuml; &nbsp;10 bin 819 kilometre olan kentin y&uuml;zde 17&rsquo;si ovalardan, y&uuml;zde 35&rsquo;i ise dağlardan oluşmaktadır. Bursa ile ilgili g&uuml;ncel hava durumu bilgilerine sayfamızdan ulaşabilir ve Bursa otob&uuml;s bileti satın alma işleminizden &ouml;nce havanın durumuyla ilgili bilgi sahibi olabilirsiniz. &nbsp;</p>
<p>Turizm a&ccedil;ısından T&uuml;rkiye&rsquo;nin &ouml;nemli illerinden biri olan Bursa&rsquo;da dağ, deniz, tarih ve kaplıca gibi turizm &ccedil;eşitleri bulunur. &Uuml;lkenin y&uuml;ksek dağları arasında yer alan Uludağ (2.543 metre) kış turizmi a&ccedil;ısından dikkat &ccedil;eken yerler arasında ilk sıralarda yer almaktadır. Gemlik ve Mudanya gibi deniz kenarında bulunan il&ccedil;elere sahip olan Bursa&rsquo;da aynı zamanda İznik ve Uluabat g&ouml;lleri yer almaktadır. UNESCO tarafından D&uuml;nya Mirası Listesi&rsquo;ne eklenen Hanlar B&ouml;lgesi ile dikkat &ccedil;eken kentin en &uuml;nl&uuml; camisi ise Ulucami&rsquo;dir. Şehirde yer alan gezilecek yerler hakkında daha detaylı bilgi i&ccedil;in sayfamızı inceleyebilir ve Bursa otob&uuml;s bileti satın alma işlemlerinizi online işlemler men&uuml;m&uuml;zden yapabilirsiniz. &nbsp;</p>
        ");

        $gezilecekler = array('Müzeler ve Ören Yerleri' => 'http://www.bursakulturturizm.gov.tr/TR,70233/muzeler-ve-oren-yerleri.html', 'Kültür ve Doğa Turizmi' => 'www.bursakulturturizm.gov.tr/TR,70234/kultur-ve-doga-turizmi.html', 'Mudanya' => 'http://www.bursakulturturizm.gov.tr/TR,70235/mudanya.html','Türbeler' => 'http://www.bursakulturturizm.gov.tr/TR,70244/turbeler.html','Camiler' => 'www.bursakulturturizm.gov.tr/TR,70236/camiler.html');
        $tpl->assign('gezilecekler', $gezilecekler);

        $tpl->assign("location_key","317350");
        $tpl->assign("g_map","https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d24348.076493335535!2d29.081757099999997!3d40.2866435!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14ca1582d8d45695%3A0x61a00555fc973392!2zQnVyc2EsIFTDvHJraXll!5e0!3m2!1str!2s!4v1417443701927");
        $tpl->assign("sehir_ulasim","https://www.burulas.com.tr/otobus-hat-sorgulama.aspx?hatAdi=99999");

        break;

    default:
        header("Location: ".$site_adress."404");
        die();
        break;
}